[window]
padding = { x = 8, y = 8 }
opacity = 1.0
decorations = "None"
startup_mode = "Windowed"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }  # Added for Sway rules

[scrolling]
history = 5000  # Reduced for lighter memory
multiplier = 3

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic" }
size = 10.0

[colors]
primary = { background = "#1e1e2e", foreground = "#cdd6f4" }
normal = { black = "#45475a", red = "#f38ba8", green = "#a6e3a1", yellow = "#f9e2af", blue = "#89b4fa", magenta = "#f5c2e7", cyan = "#94e2d5", white = "#bac2de" }
bright = { black = "#585b70", red = "#f38ba8", green = "#a6e3a1", yellow = "#f9e2af", blue = "#89b4fa", magenta = "#f5c2e7", cyan = "#94e2d5", white = "#a6adc8" }

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true

[keyboard]
bindings = [
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
]

[mouse]
hide_when_typing = true

[general]
live_config_reload = true

[terminal.shell]
program = "/usr/bin/fish"  # Set fish as default shell
args = ["--login"]  # Ensure fish loads profile

[env]
TERM = "alacritty"
