[window]
padding = { x = 8, y = 8 }
opacity = 1.0
decorations = "None"
startup_mode = "Windowed"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
[scrolling]
history = 5000
multiplier = 3
[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic" }
size = 10.0
[colors]
primary = { background = "#000000", foreground = "#f8f8f2" }
normal = { black = "#75715e", red = "#f92672", green = "#a6e22e", yellow = "#e6db74", blue = "#66d9ef", magenta = "#ae81ff", cyan = "#66d9ef", white = "#f8f8f2" }
bright = { black = "#75715e", red = "#f92672", green = "#a6e22e", yellow = "#e6db74", blue = "#66d9ef", magenta = "#ae81ff", cyan = "#66d9ef", white = "#f8f8f0" }
[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
[keyboard]
bindings = [
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
]
[mouse]
hide_when_typing = true
[general]
live_config_reload = true
[terminal.shell]
program = "/usr/bin/fish"
args = ["--login"]
[env]
TERM = "alacritty"
